### PR TITLE
Add XSDL server startup script

### PR DESCRIPTION
**Pull request by luongthomas**
screenshot_20190128-155030_xserver xsdl

### CODE REVIEW

**Comment by carbonatedcaffeine** [comment]
How About Alpine? Why Does My Project Not Get It?

**Comment by luongthomas** [comment]
Once Alpine becomes available for testing, I'll test if the XSDL script works for it.

**Comment by carbonatedcaffeine** [comment]
thanks

**Comment by carbonatedcaffeine** [comment]
it will be available soon.

**Pull request merged**
